# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# encoding: UTF-8


School.create({
  name: "Becari Language School", website: "http://www.becari.com.mx/", city: "Oaxaca City", address: "M. Bravo 210, Plaza Cristóbal", phone: "+52 (951) 514-6076", email: "becari@becari.com.mx", summary: "At the Becari Language School, we specialize in offering many different options for any person interested in learning our beautiful Spanish language. To study at Becari is not only to learn a new language but also to enter another culture. We are a medium size school which prides itself on careful and sustained attention to each student regardless of his or her level of proficiency with a staff of qualified teachers. who have ample experience in the field of Spanish as a second language. Watch our video showing Becari in action! • Medium size school • Professional teachers • Over 50% of our students arrive by recommendation • Diploma after 2 weeks • Carefully selected and monitored Mexican families • Numerous social activities • Students ID/Discounts card • Oaxaca Airport pick-up and homestay drop-off • Intercambios • Wireless Internet Access and Fax • Cell phones available for students • One time enrollment fee • Bildungsurlaub for students in Frankfurt, Germany", methods: "", mayan_lang: "true", childrens_prog: "true", teens_prog: "", seniors_prog: "", professional_prog: "true", sp_teachers_prog: "", distance_edu: "", test_prep: "", other_prog_descrip: "", disability_accesib: "", airport_pickup: "", img3: "http://farm9.static.flickr.com/8534/8644370010_66b087edbf_b.jpg", img4: "http://farm6.static.flickr.com/5335/6941963824_09ecdb557c_b.jpg", img5: "http://farm9.static.flickr.com/8229/8549400592_747840d5e1.jpg", admin_fee: 70, per_hr_private: 17, per_hr_group: 10, max_students_per_class: nil, homestay_price: 126
  })

Course.create({
    school_id: 1, name: "Regular", hrs_per_wk: 15 , price: 150, price_change: "no", description: "Three hours of classes, five days a week, divided into two sessions with a different teacher for each session. The first session includes a review of specific grammar points through dynamic and interactive learning. In the second session, the student practice what they have learned through conversation and practical exercises. There is fifteen minute break between the two sessions. Classes run from 9:00 a.m. to 12:00 p.m. or 4:00 to 7:00 p.m.", homestay_incl: false
  })

Course.create({
    school_id: 1, name: "Intensive", hrs_per_wk: 20, price: 200, price_change: "no", description: "Four hours of classes, five days a week, divided evenly between two teachers. This program allows student to dedicate more time to developing conversational skills. There is also a fifteen minute break. Classes run from 9:00 a.m. to 1:00 p.m. or 3:00 to 7:00 p.m.", homestay_incl: false
  })

Course.create({
    school_id: 1, name: "Super-Intensive", hrs_per_wk: 30, price: 300, price_change: "no", description: "Six hours of class five days a week divided in to three sessions, each with a different teacher. There is a fifteen minute break between the first two sessions. The last session is held after la comida (between 4 and 5:00 p.m.). This program is recommended for students who do not have a lot of time to spend in Oaxaca and really want to improve their language skills quickly", homestay_incl: false
  })

Course.create({
    school_id: 1, name: "Super-Intensive Workshop", hrs_per_wk: 30, price: 320, price_change: "no", description: "Four hours of regular Spanish classes five days a week divided in two sessions, each a with a different teacher. And two more hours of workshops in the afternoon, 4:00 - 6:00 p.m. Monday and Friday: Weaving. Tuesday and Thursday: Ceramics. Wednesday: Cooking", homestay_incl: false
  })



School.create({
  name: "Amigos Del Sol", website: "http://www.oaxacanews.com/amigosdelsol.htm", city: "Oaxaca City", address: "Calzada San Felipe del Agua #322", phone: "", email: "", summary: "WELCOME TO AMIGOS DEL SOL! We enjoy meeting nice people from all over the world. We have been teaching for 16 years. Our teachers have many years of experience. Only 3 students per class at the same Spanish Level. Conversational Spanish while learning grammar. Relaxed but formal classes. Flexible schedule. Intercambios, tours, cooking lessons. Transportation service. Wifi", methods: "", mayan_lang: "", childrens_prog: "", teens_prog: "", seniors_prog: "", professional_prog: "", sp_teachers_prog: "", distance_edu: "", test_prep: "", other_prog_descrip: "", disability_accesib: "", airport_pickup: "", img3: "http://www.oaxacanews.com/oaxaca/Icons/Photos/2012/school%2013%202012.jpg", img4: "http://www.oaxacanews.com/oaxaca/Icons/Photos/2012/school%2011%202012.jpg", img5: "http://www.oaxacanews.com/oaxaca/Icons/Photos/2011/school%2027%202012.jpg", admin_fee: 0, per_hr_private: 16, per_hr_group: 10, max_students_per_class: 3, homestay_price: 154
  })

School.create({
  name: "Instituto Cultural Oaxaca", website: "http://www.icomexico.com/", city: "Oaxaca City", address: "Avenida Juarez #909", phone: "", email: "", summary: "Located on the grounds of a beautiful 19th century estate, our Spanish language school has proudly welcomed students from all over the world. Our school offers you personal and friendly service and the opportunity to learn Spanish in the stunning, colonial city of Oaxaca – a place where historic and present-day Mexico meet.<br />Spanish schoolThe Institute is a founding member of ASESEO, the Spanish Language Schools Association of Oaxaca, an organization dedicated to ensure quality and professionalism in Spanish language learning and to promote Oaxaca and its culture as a destination to study Spanish.<br />Whatever Spanish language program you decide is right for you, our enthusiastic and dynamic native-speakers, all who have university degrees and years of teaching experience, will teach you exclusively in Spanish so your language learning is done in an environment of total Spanish immersion. Teachers implement strategies that facilitate language acquisition and evaluation throughout the learning process; providing individualized feedback and assistance. In some cases, completion may serve as credit for a university program.", methods: "Our methodology is based on the Common European Framework of Reference for Languages (CEFR) and our classes are developed within the Communicative Model, which focuses on the need to understand and use the fundamentals of the language on a daily basis. The Spanish language programs are undertaken in a vibrant and friendly atmosphere with the goal of broadening your skills and confidence through total immersion. We place special emphasis on: * Linguistic and cultural content * Spoken communication * Listening * Reading * Writing skills.", mayan_lang: "", childrens_prog: "true", teens_prog: "", seniors_prog: "", professional_prog: "true", sp_teachers_prog: "true", distance_edu: "true", test_prep: "true", other_prog_descrip: "", disability_accesib: "", airport_pickup: "", img3: "http://www.linguaserviceworldwide.com/wp-content/uploads/2013/02/47433255.jpg", img4: "http://4.bp.blogspot.com/-9nQMPXyYa5Q/TZ6Wa8Ze4pI/AAAAAAAAAD8/mnigjhdk7t4/s320/IMG_2710.jpg", img5: "http://res.cloudinary.com/abroad101/image/upload/w_800,h_800,c_limit/v1347746814/dc3d.jpg", admin_fee: 55, per_hr_private: 19, per_hr_group: nil, max_students_per_class: nil
  })

School.create({
  name: "Academia Vinigúlaza", website: "http://www.vinigulaza.com", city: "Oaxaca City", address: "Abasolo #503, 68000 Oaxaca, Oaxaca", phone: "(951) 513-2763", email: "info@vinigulaza.com", summary: "Academia Vinigúlaza, a successful language school offering Spanish classes in Oaxaca for over 10 years, specialises in personalised classes for small groups. Teachers foster an atmosphere of confidence and fun in the classroom offering patient support and focusing on dynamic conversation exercises to allow students maximum speaking time. We know your time is valuable and often limited; we work with you to improve your Spanish fast and enjoyably. Our Spanish courses are with small groups of 2 to 6 students and our Spanish teachers are all fully-trained, native speakers with an exceptional amount of patience. The students feel relaxed because our teachers make them feel comfortable about using the language.", methods: "", mayan_lang: "", childrens_prog: "", teens_prog: "", seniors_prog: "", professional_prog: "", sp_teachers_prog: "", distance_edu: "", test_prep: "", other_prog_descrip: "", disability_accesib: "", airport_pickup: "", img3: "https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-ash2/t1.0-9/430699_367512676622043_636488587_n.jpg", img4: "https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-ash2/t1.0-9/421621_367944149912229_77423780_n.jpg", img5: "https://scontent-b-mia.xx.fbcdn.net/hphotos-frc3/t1.0-9/430151_367918659914778_1518075756_n.jpg", admin_fee: nil, per_hr_private: nil, per_hr_group: nil, max_students_per_class: nil
  })

School.create({
  name: "Oaxaca International Language School", website: "www.oaxacainternational.com", city: "Oaxaca City", address: "Libres # 207, Colonia Centro", phone: "+52 (951) 514-8304, (951) 514-7324 & (951) 503-4228", email: "oaxaca@oaxacainternational.com", summary: "Welcome to Oaxaca International 'Something more than Spanish' we hope that you will form a part of our group of students who learn our beautiful language and, at the same time, learn about our culture, customs, and traditions. Here you will get to meet people from diverse parts of the world, share your experiences, knowledge; and make new friends. Oaxaca International welcomes students without regard to sex, age, race, religion, or social status. Oaxaca International not only offers classes for young and mature students--children are also welcome. For children we offer a special and entertaining educational program that includes activities such as workshops for making typical Oaxacan wooden toys and piñatas, as well as field trips to local interesting places.", methods: "", mayan_lang: "", childrens_prog: "true", teens_prog: "", seniors_prog: "", professional_prog: "", sp_teachers_prog: "", distance_edu: "", test_prep: "", other_prog_descrip: "", disability_accesib: "", airport_pickup: "", img3: "http://www.oaxacainternational.com/images/aboutus2.jpg", img4: "http://oaxacainternational.com/f7.jpg", img5: "http://oaxacainternational.com/f5.jpg", admin_fee: 0, per_hr_private: 13, per_hr_group: nil, max_students_per_class: 4
  })

School.create({
  name: "Español Interactivo", website: "www.studyspanishinoaxaca.com", city: "Oaxaca City", address: "Armenta y López No. 311-B Centro Histórico", phone: "+52 (951) 514-8304, (951) 514-7324 & (951) 503-4228", email: "oaxaca@oaxacainternational.com", summary: "Learning based on interaction. -Pleasent sessions with real communication-A wide variety of flexible programs for every one.-We adapt ourselves to your agenda the entire year, even on holidays.-Special packages for the Days of the Dead, Christmas, Holy week and Guelaguetza..", methods: "At Español Interactivo, we teach you to effectively interact verbally, by constantly giving you opportunities to express your own ideas, and understand others' ideas. Thus our name: Español Interactivo.<br />Our class materials contain relevant language meant for practical usage and designed to enhance your creativity: like a Lego set that helps structure your ideas, you will learn how to use this Spanish to communicate, starting on Day 1 of your course.<br />In conversation sessions, you don't need to understand every single word you hear. It's important to understand both verbal and body language. Concentrate on the message. Word-by-word translation makes you lose focus on the language you're learning. If you focus too much on every word, you get tense: you'll miss the overall message and feel frustrated. In every class, you learn a little more, and you will understand and express yourself that much better.<br />Enjoy this great opportunity you've given yourself to learn or improve your Spanish. Learning a language is an ongoing process, so relax and make yourself comfortable.", methods: "", mayan_lang: "", childrens_prog: "", teens_prog: "", seniors_prog: "", professional_prog: "true", sp_teachers_prog: "", distance_edu: "true", test_prep: "true", other_prog_descrip: "true", disability_accesib: "", airport_pickup: "", img3: "http://www.oaxacainternational.com/images/aboutus2.jpg", img4: "http://oaxacainternational.com/f7.jpg", img5: "http://oaxacainternational.com/f5.jpg", admin_fee: 0, per_hr_private: 17, per_hr_group: nil, max_students_per_class: nil
  })


